mode=run
mask=0x428
order=libctest,cyclictest,unixbench
timeout_libctest=180
timeout_cyclictest=120
timeout_unixbench=180
ltp_exclude=
ltp_include=
ltp_exclude_musl=
ltp_exclude_glibc=
ltp_libc=both
ltp_runner=script
ltp_from=
