services:
  os-dev:
    image: zhouzhouyi/os-contest:20260510
    pull_policy: missing
    network_mode: host
    command: ["sleep", "infinity"]
    privileged: true
    devices:
      - /dev/loop-control:/dev/loop-control
      - /dev/loop0:/dev/loop0
    device_cgroup_rules:
      - "c 10:237 rmw"
      - "b 7:* rmw"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MODE=release
    tty: true
    stdin_open: true
    working_dir: /app

    # IO 限速：每人 40MB/s，磁盘顺序写 ~94MB/s
    # 注意：必须用整盘 /dev/sdb 而非分区 /dev/sdb2，blkio 对分区不生效
    blkio_config:
      device_read_bps:
        - path: /dev/sdb
          rate: "40m"
      device_write_bps:
        - path: /dev/sdb
          rate: "40m"
