## initproc runtime config
## mode: run | shell | run_then_shell
mode=run

## 12-bit testcase mask (bit0..bit11):
## bit0=basic, bit1=busybox, bit2=lua, bit3=libctest,
## bit4=iozone, bit5=unixbench, bit6=iperf, bit7=libcbench,
## bit8=lmbench, bit9=netperf, bit10=cyclictest, bit11=ltp
## examples:
##   0x001 => only basic
##   0x103 => basic + busybox + lmbench
##   0xFFF => all 12 groups
mask=0x800

## LTP exclude list (comma-separated)
ltp_exclude=


## LTP include list (auto-populated by , comma-separated)
## 非空时只跑此列表中的测例（再经过 exclude 过滤）先跑的include再跑的exlucde,是不是问题在这呢
ltp_include=abs01,accept01,abort01,kill09,kill11,kill12,chown01,chdir04,chmod01,chown02,chown05,clock_gettime02,clock_nanosleep01,clone04,clone07,clone08,clone302,close01,clone03,close02,clock_nanosleep04,connect01,clone06,confstr01,clone01,accept03,accept4_01,creat01,creat03,creat05,crash02,data_space,diotest02,diotest03,diotest01,diotest4,diotest06,diotest05,dup07,dup202,dup03,dup203,dup205,dup01,dup3_01,dup06,dup207,dup204,dup206,dup04,dup02,dup201,epoll01,epoll_create1_02,epoll_create02,execv01_child,epoll_create01,execle01_child,execve01_child,execlp01_child,exit02,fchmodat01,faccessat01,fcntl02,fchmod01,fcntl05,fallocate03,exit_group01,fcntl12,fchownat01,fcntl04,execvp01_child,faccessat02,fchmodat02,fcntl08,exit01,fallocate01,fcntl03,faccessat201,fcntl14,alarm02,asapi_01,alarm05,alarm03,alarm06,alarm07,fcntl29,atof01,bind01,bind03,flock06,fork07,fork04,fork10,fork03,fork08,fork09,fork01,fptest02,fpathconf01,fptest01,fork_procs,fstat03,fstatat01,ftest02,ftest06,futex_wait01,ftruncate03,futex_cmp_requeue02,ftruncate01,futex_wait02,futex_wait04,futex_wake01,brk01,brk02,getpgid01,getcwd01,geteuid02,getrusage01,gethostname01,getrandom02,getdents02,geteuid01,getpagesize01,getpeername01,getpgrp01,getppid02,getpid02,getrlimit01,getrlimit02,getrandom04,getdomainname01,getcwd02,getsockopt01,getsockname01,gettimeofday02,getuid01,getuid03,growfiles,in6_01,ioctl_ns07
# LTP musl-specific exclude (auto-populated by )
ltp_exclude_musl=accept02,af_alg02,assign_password.sh,bind04,bind05,binfmt_misc02.sh,cgroup_regression_3_1.sh,cgroup_regression_3_2.sh,cgroup_regression_5_1.sh,cgroup_regression_5_2.sh,cgroup_regression_6_1.sh,cgroup_regression_6_2.sh,cgroup_regression_fork_processes,cleanup_lvm.sh,clock_gettime04,clock_nanosleep02,cp_tests.sh,cpuhotplug04.sh,cpuhotplug_do_disk_write_loop,cpuhotplug_do_spin_loop,crash01,create_datafile,cve-2017-17052,dio_sparse,diotest4,doio,ebizzy,execve06,fcntl18,fcntl18_64,fcntl34,fcntl34_64,fcntl36,fcntl36_64,float_bessel,float_exp_log,float_iperb,float_power,float_trigo,force_erase.sh,fork14,fork_exec_loop,fs_bind09.sh,fs_bind_move07.sh,fs_bind_move11.sh,fs_bind_move12.sh,fs_bind_move22.sh,fs_bind_rbind13.sh,fs_bind_rbind22.sh,fs_bind_rbind23.sh,fs_bind_rbind24.sh,fs_racer_dir_test.sh,fs_racer_file_list.sh,fstat03,fstat03_64,fstatfs02,fstatfs02_64,fsync02,ftest04,ftest08,futex_wait03,futex_wait05,futex_wake02,genacos,genasin,genatan,genatan2,genceil,gencos,gencosh,genexp,genfabs,genfloor,genfmod,genfrexp,genhypot,genj0,genj1,genldexp,genlgamma,genlog,genlog10,genmodf,genpow,gensin,gensinh,gensqrt,gentan,gentanh,geny0,geny1,getrusage01,getrusage02,gettid02,icmp4-multi-diffip04,inode02,insmod01.sh,isofs.sh,kcmp03,kill02,kill08,kill10,kill11,ldd01.sh,lftest,ln_tests.sh,logrotate_tests.sh,lsmod01.sh,ltpSockets.sh
## LTP glibc-specific exclude (auto-populated by )
ltp_exclude_glibc=crash02,diotest4,fstat03,getrusage01,inode01,kill11
## LTP libc filter: musl | glibc | both (default: both)
ltp_libc=both

ltp_runner=inline







ltp_from=
