mode=run
mask=0x800
ltp_runner=suite
ltp_libc=both
ltp_suites=smoketest,syscalls,syscalls-ipc,fs,fs_bind,mm,sched,nptl,pty,ipc,capability,fcntl-locktests
ltp_exclude=
ltp_exclude_musl=
ltp_exclude_glibc=
ltp_include=
ltp_from=
diag=1

