// Shared code extracted from fs.rs — used by all syscall function files.
// Auto-generated by split_fs.py during refactoring step 1.

use crate::fs::dev::pipe::Pipe;
pub(crate) use crate::fs::poll::{ppoll, pselect, FdSet, PollFd};
pub(crate) use crate::fs::vfs::fcntl::{FcntlCommand, PosixFlock, F_UNLCK};
pub(crate) use crate::fs::vfs::posix_lock::{
    init_posix_lock_manager, mgr, posix_lock_get, posix_lock_set, release_posix_for_owner, LockKey,
    LockOwner,
};
pub(crate) use crate::fs::vfs::{self, FileFlags, FileType, SeekFrom, SuperBlock};
pub(crate) use crate::fs::*;
pub(crate) use crate::mm::{
    check_user_range, MapPermission, UserBufferReader, UserBufferWriter, UserCString, UserIoVec,
    UserPtr, UserPtrMut, UserSlice, VirtAddr,
};
pub(crate) use crate::syscall::errno::*;
pub(crate) use crate::syscall::utils::wait_io_core;
pub(crate) use crate::task::{
    current_task, current_user_token, find_process_by_pid, find_task_by_tid,
    is_executable_inode_busy, is_writable_inode_busy, signal::Signals, WaitQueue, WaitResult,
};
pub(crate) use crate::timer::{current_timespec, TimeSpec};
pub(crate) use crate::utils::error::SyscallErr;
pub(crate) use alloc::boxed::Box;
pub(crate) use alloc::collections::{BTreeMap, VecDeque};
pub(crate) use alloc::string::String;
pub(crate) use alloc::sync::Arc;
pub(crate) use alloc::vec::Vec;
pub(crate) use core::mem::size_of;
pub(crate) use core::panic;
pub(crate) use core::sync::atomic::{AtomicUsize, Ordering};
pub(crate) use lazy_static::lazy_static;
pub(crate) use log::{debug, error, info, trace, warn};
pub(crate) use num_enum::TryFromPrimitive;

pub(crate) const OPEN_ACCMODE_MASK: u32 = 0o3;
pub(crate) const MFD_CLOEXEC: u32 = 0x0001;
pub(crate) const MFD_ALLOW_SEALING: u32 = 0x0002;
pub(crate) const MFD_HUGETLB: u32 = 0x0004;
pub(crate) const MFD_HUGE_SHIFT: u32 = 26;
pub(crate) const MFD_HUGE_MASK: u32 = 0x3f << MFD_HUGE_SHIFT;
pub(crate) const MFD_VALID_FLAGS: u32 =
    MFD_CLOEXEC | MFD_ALLOW_SEALING | MFD_HUGETLB | MFD_HUGE_MASK;
pub(crate) const MEMFD_NAME_MAX: usize = 249;
pub(crate) static MEMFD_COUNTER: AtomicUsize = AtomicUsize::new(0);

pub(crate) const SEEK_SET: i16 = 0;
pub(crate) const SEEK_CUR: i16 = 1;
pub(crate) const SEEK_END: i16 = 2;
pub(crate) const LOCK_SH: u32 = 1;
pub(crate) const LOCK_EX: u32 = 2;
pub(crate) const LOCK_NB: u32 = 4;
pub(crate) const LOCK_UN: u32 = 8;

#[derive(Clone, Copy, Debug)]
pub(crate) struct FlockLock {
    pub(crate) key: LockKey,
    pub(crate) owner_description: usize,
    pub(crate) exclusive: bool,
}

lazy_static! {
    pub(crate) static ref FLOCK_LOCKS: spin::Mutex<Vec<FlockLock>> = spin::Mutex::new(Vec::new());
}

pub const AT_FDCWD: usize = 100usize.wrapping_neg();
pub const AT_EMPTY_PATH: u32 = 0x1000;
pub const AT_SYMLINK_NOFOLLOW: u32 = 0x100;
pub const AT_REMOVEDIR: u32 = 0x200;
pub const AT_SYMLINK_FOLLOW: u32 = 0x400;

/// 将旧的 OpenFlags 转换为新的 VFS FileFlags
pub(crate) fn _open_flags_to_vfs_flags(o: OpenFlags) -> vfs::FileFlags {
    let mut f = vfs::FileFlags::empty();
    if o.contains(OpenFlags::O_RDONLY) {
        f.insert(vfs::FileFlags::O_RDONLY);
    }
    if o.contains(OpenFlags::O_WRONLY) {
        f.insert(vfs::FileFlags::O_WRONLY);
    }
    if o.contains(OpenFlags::O_RDWR) {
        f.insert(vfs::FileFlags::O_RDWR);
    }
    if o.contains(OpenFlags::O_CREAT) {
        f.insert(vfs::FileFlags::O_CREAT);
    }
    if o.contains(OpenFlags::O_TRUNC) {
        f.insert(vfs::FileFlags::O_TRUNC);
    }
    if o.contains(OpenFlags::O_APPEND) {
        f.insert(vfs::FileFlags::O_APPEND);
    }
    if o.contains(OpenFlags::O_NONBLOCK) {
        f.insert(vfs::FileFlags::O_NONBLOCK);
    }
    if o.contains(OpenFlags::O_DIRECTORY) {
        f.insert(vfs::FileFlags::O_DIRECTORY);
    }
    if o.contains(OpenFlags::O_CLOEXEC) {
        f.insert(vfs::FileFlags::O_CLOEXEC);
    }
    if o.contains(OpenFlags::O_NOFOLLOW) {
        f.insert(vfs::FileFlags::O_NOFOLLOW);
    }
    if o.contains(OpenFlags::O_PATH) {
        f.insert(vfs::FileFlags::O_PATH);
    }
    f
}

/// 从 dirfd 解析起始 IndexNode（用于路径操作）
pub(crate) fn resolve_start_inode(dirfd: usize) -> Result<Arc<dyn vfs::IndexNode>, isize> {
    let task = current_task().unwrap();
    Ok(match dirfd {
        AT_FDCWD => task.process.fs().lock().working_inode.inode.clone(),
        fd => {
            let files_ref = task.process.files();
            let fd_table = files_ref.lock();
            fd_table
                .get_file(fd)
                .map_err(|e| -(e as isize))?
                .inode
                .clone()
        }
    })
}

/// cwd 路径规范化：处理绝对/相对 chdir，处理 .  ..  //  trailing/
pub(crate) fn normalize_cwd(old_path: &str, new_path: &str) -> alloc::string::String {
    let mut parts: alloc::vec::Vec<&str> = alloc::vec::Vec::new();
    if !new_path.starts_with('/') {
        for p in old_path.split('/') {
            if !p.is_empty() {
                parts.push(p);
            }
        }
    }
    for p in new_path.split('/') {
        match p {
            "" | "." => {}
            ".." => {
                parts.pop();
            }
            _ => parts.push(p),
        }
    }
    if parts.is_empty() {
        alloc::string::String::from("/")
    } else {
        let mut s = alloc::string::String::with_capacity(
            parts.iter().map(|p| p.len()).sum::<usize>() + parts.len(),
        );
        for p in parts {
            s.push('/');
            s.push_str(p);
        }
        s
    }
}

pub(crate) fn user_cstring(token: usize, ptr: *const u8) -> Result<String, isize> {
    UserCString::new(ptr).read(token)
}

pub(crate) fn validate_memfd_flags(flags: u32) -> Result<(), SyscallErr> {
    if (flags & !MFD_VALID_FLAGS) != 0 {
        return Err(SyscallErr::EINVAL);
    }
    if (flags & MFD_HUGE_MASK) != 0 && (flags & MFD_HUGETLB) == 0 {
        return Err(SyscallErr::EINVAL);
    }
    if (flags & MFD_HUGETLB) != 0 {
        return Err(SyscallErr::ENODEV);
    }
    Ok(())
}

pub(crate) fn validate_path_len(path: &str) -> Result<(), isize> {
    if path.len() >= vfs::MAX_PATHLEN {
        return Err(ENAMETOOLONG);
    }
    if path
        .split('/')
        .any(|component| component.len() > vfs::NAME_MAX)
    {
        return Err(ENAMETOOLONG);
    }
    Ok(())
}

pub(crate) fn open_subject_ids() -> (u32, u32) {
    let task = current_task().unwrap();
    let inner = task.acquire_inner_lock();
    (inner.fsuid, inner.fsgid)
}

pub(crate) fn open_requests_write(flags: OpenFlags) -> bool {
    let access_mode = flags.bits() & OPEN_ACCMODE_MASK;
    access_mode == OpenFlags::O_WRONLY.bits()
        || access_mode == OpenFlags::O_RDWR.bits()
        || flags.contains(OpenFlags::O_TRUNC)
}

#[inline]
pub(crate) fn offset_is_negative(offset: usize) -> bool {
    offset > isize::MAX as usize
}

#[inline]
pub(crate) fn is_stream_file(file: &vfs::File) -> bool {
    file.mode().contains(vfs::FileMode::FMODE_STREAM)
}

pub(crate) fn is_path_fd(file: &vfs::File) -> bool {
    file.mode().contains(vfs::FileMode::FMODE_PATH) || file.flags().contains(vfs::FileFlags::O_PATH)
}

pub(crate) fn has_directory_write_search_access(
    meta: &vfs::Metadata,
    uid: u32,
    gid: u32,
    groups: &[u32],
) -> bool {
    if uid == 0 {
        return true;
    }
    (permission_class_bits(meta, uid, gid, groups) & 0o3) == 0o3
}

pub(crate) fn apply_created_inode_metadata(
    parent_meta: &vfs::Metadata,
    inode: &Arc<dyn vfs::IndexNode>,
    mode: vfs::InodeMode,
    uid: u32,
    gid: u32,
) -> Result<(), isize> {
    let mut meta = inode.metadata().map_err(|e| -(e as isize))?;
    let parent_setgid = parent_meta.mode.contains(vfs::InodeMode::S_ISGID);
    let child_gid = if parent_setgid { parent_meta.gid } else { gid };

    meta.uid = uid;
    meta.gid = child_gid;
    meta.mode = vfs::InodeMode::from(meta.file_type) | (mode & vfs::InodeMode::S_IALLUGO);
    if meta.mode.contains(vfs::InodeMode::S_ISGID) && uid != 0 && gid != child_gid {
        meta.mode.remove(vfs::InodeMode::S_ISGID);
    }

    match inode.set_metadata(&meta) {
        Ok(()) | Err(SyscallErr::ENOSYS) => Ok(()),
        Err(e) => Err(-(e as isize)),
    }
}

pub(crate) fn apply_current_umask(mode: vfs::InodeMode) -> vfs::InodeMode {
    let task = current_task().unwrap();
    let fs_ref = task.process.fs();
    let mask = fs_ref.lock().umask & 0o777;
    // Only apply umask to permission bits (S_IALLUGO).
    // Callers that need S_IFMT type bits (mknodat) must re-pack them
    // from the extracted FileType after calling this function.
    let perm_bits = mode & vfs::InodeMode::S_IALLUGO;
    perm_bits & !vfs::InodeMode::from_bits_truncate(mask)
}

pub(crate) fn metadata_to_stat(meta: &vfs::Metadata) -> Stat {
    Stat {
        st_dev: meta.dev_id as u64,
        st_ino: meta.inode_id as u64,
        st_mode: meta.mode.bits() | vfs::InodeMode::from(meta.file_type).bits(),
        st_nlink: meta.nlinks as u32,
        st_uid: meta.uid,
        st_gid: meta.gid,
        st_rdev: meta.raw_dev as u64,
        __pad: 0,
        st_size: meta.size,
        st_blksize: meta.blk_size as u32,
        __pad2: 0,
        st_blocks: meta.blocks as u64,
        st_atime: meta.atime,
        st_mtime: meta.mtime,
        st_ctime: meta.ctime,
        __unused: 0,
    }
}

pub(crate) fn metadata_to_statx(meta: &vfs::Metadata, _mask: u32) -> Statx {
    let stat = metadata_to_stat(meta);
    // Linux 6.6: stx_mask reports STATX_BASIC_STATS — the fields this
    // implementation always fills, regardless of what was requested.
    let actual_mask = STATX_BASIC_STATS;
    let mut statx = Statx::new(
        actual_mask,
        stat.get_nlink(),
        stat.get_mode() as u16,
        stat.get_ino() as u64,
        stat.get_size() as u64,
        stat.get_atime() as i64,
        stat.get_ctime() as i64,
        stat.get_mtime() as i64,
        ((stat.get_rdev() & 0xffff_00) >> 8) as u32,
        (stat.get_rdev() & 0xff) as u32,
        ((stat.get_dev() & 0xffff_00) >> 8) as u32,
        (stat.get_dev() & 0xff) as u32,
    );
    statx.stx_uid = stat.st_uid;
    statx.stx_gid = stat.st_gid;
    // Use metadata-backed block size (filesystem preferred I/O size).
    statx.stx_blksize = meta.blk_size as u32;
    // Use metadata-backed block count in 512-byte units.
    statx.stx_blocks = meta.blocks as u64;
    statx
}

pub(crate) fn open_file_at(
    dirfd: usize,
    path: &str,
    flags: OpenFlags,
    mode: vfs::InodeMode,
) -> Result<Arc<vfs::File>, isize> {
    let start = if path.starts_with('/') {
        crate::fs::current_root_inode()
    } else {
        resolve_start_inode(dirfd)?
    };
    if path.is_empty() {
        let md = start.metadata().map_err(|e| -(e as isize))?;
        return Ok(vfs::File::new_without_open(
            start,
            _open_flags_to_vfs_flags(flags),
            md.file_type,
        ));
    }

    // Paths like ".", "./", ".//" resolve to the start inode itself
    if path == "." || path.trim_end_matches('/') == "." {
        // O_TMPFILE is not supported. apk uses openat(cache_fd, ".", O_TMPFILE|...)
        // to create unnamed temp files. If we open the directory as writable,
        // the subsequent write() returns EISDIR and apk sees "Is a directory".
        // Return EOPNOTSUPP so userspace falls back to named temp files.
        if flags.contains(OpenFlags::O_TMPFILE) {
            return Err(crate::syscall::errno::EOPNOTSUPP);
        }
        let md = start.metadata().map_err(|e| -(e as isize))?;
        if flags.contains(OpenFlags::O_CREAT | OpenFlags::O_EXCL) {
            return Err(EEXIST);
        }
        if flags.contains(OpenFlags::O_PATH) {
            return Ok(vfs::File::new_without_open(
                start,
                vfs::FileFlags::from_bits_truncate(
                    vfs::FileFlags::O_DIRECTORY.bits()
                        | vfs::FileFlags::O_NOFOLLOW.bits()
                        | vfs::FileFlags::O_PATH.bits()
                        | vfs::FileFlags::O_CLOEXEC.bits(),
                ) & _open_flags_to_vfs_flags(flags),
                md.file_type,
            ));
        }
        if flags.contains(OpenFlags::O_DIRECTORY) && md.file_type != FileType::Dir {
            return Err(ENOTDIR);
        }
        return vfs::File::new_with_metadata(start, _open_flags_to_vfs_flags(flags), md)
            .map_err(|e| -(e as isize));
    }

    let (uid, fsgid, groups) = caller_ids_and_groups();
    // uid==0 (root) bypasses DAC — skip the redundant path walk
    if uid != 0 {
        let parent_result = check_parent_search_access(&start, path, uid, fsgid, &groups);
        if parent_result != SUCCESS {
            return Err(parent_result);
        }
    }

    let follow_final = !flags.contains(OpenFlags::O_NOFOLLOW);
    match vfs_lookup(&start, path, follow_final) {
        Ok(target) => {
            // O_PATH + O_NOFOLLOW opens the symlink itself, not ELOOP (Linux semantics)
            if !follow_final && !flags.contains(OpenFlags::O_PATH) {
                if let Ok(md) = target.metadata() {
                    if md.file_type == FileType::SymLink {
                        return Err(ELOOP);
                    }
                }
            }
            if flags.contains(OpenFlags::O_CREAT | OpenFlags::O_EXCL) {
                return Err(EEXIST);
            }
            let md = target.metadata().map_err(|e| -(e as isize))?;

            // O_DIRECTORY must fail ENOTDIR before any special-case handling.
            // Previously this check was after the FIFO branch, making it unreachable
            // for named FIFOs — open(fifo, O_DIRECTORY) would succeed instead of ENOTDIR.
            if flags.contains(OpenFlags::O_DIRECTORY) && md.file_type != FileType::Dir {
                return Err(ENOTDIR);
            }

            // O_PATH: skip all permission checks and side effects — just build a path-only fd.
            // Linux v6.6: O_PATH masks flags to O_DIRECTORY|O_NOFOLLOW|O_PATH|O_CLOEXEC,
            // dispatches to do_o_path() bypassing may_open() entirely.
            if flags.contains(OpenFlags::O_PATH) {
                return Ok(vfs::File::new_without_open(
                    target,
                    vfs::FileFlags::from_bits_truncate(
                        vfs::FileFlags::O_DIRECTORY.bits()
                            | vfs::FileFlags::O_NOFOLLOW.bits()
                            | vfs::FileFlags::O_PATH.bits()
                            | vfs::FileFlags::O_CLOEXEC.bits(),
                    ) & _open_flags_to_vfs_flags(flags),
                    md.file_type,
                ));
            }

            // Read permission check (Linux: O_RDONLY→MAY_READ, O_RDWR→MAY_READ|MAY_WRITE)
            // Applies to ALL file types (regular, FIFO, device, socket) — not just regular files.
            // O_RDONLY is the default (flags & 3 == 0) — must still check MAY_READ.
            // Skip for O_PATH (already returned early above).
            let access_mode = flags.bits() & 0o3;
            if access_mode == 0 || access_mode == 2 {
                // O_RDONLY (0) or O_RDWR (2) — both need MAY_READ
                if !has_final_access(&md, FaccessatMode::R_OK, uid, fsgid, &groups) {
                    return Err(EACCES);
                }
            }

            // O_NOATIME: check that caller is owner, group member, or root
            if flags.contains(OpenFlags::O_NOATIME) {
                let (uid, _gid) = open_subject_ids();
                if uid != 0 && uid != md.uid {
                    return Err(EPERM);
                }
            }
            // Named FIFO: substitute the filesystem inode with a Pipe-backed inode
            if md.file_type == FileType::Pipe {
                const O_ACCMODE: u32 = 0o3;
                let access = flags.bits() & O_ACCMODE;
                let for_read = access != OpenFlags::O_WRONLY.bits();
                let for_write =
                    access == OpenFlags::O_WRONLY.bits() || access == OpenFlags::O_RDWR.bits();
                return match crate::fs::dev::pipe::fifo_open(
                    (md.dev_id, md.inode_id),
                    for_read,
                    for_write,
                    flags.contains(OpenFlags::O_NONBLOCK),
                ) {
                    Ok(pipe_inode) => Ok(vfs::File::new_without_open(
                        pipe_inode,
                        _open_flags_to_vfs_flags(flags),
                        vfs::FileType::Pipe,
                    )),
                    Err(e) => Err(-(e as isize)),
                };
            }
            if md.file_type == FileType::Dir
                && (flags.contains(OpenFlags::O_WRONLY)
                    || flags.contains(OpenFlags::O_RDWR)
                    || flags.contains(OpenFlags::O_CREAT))
            {
                // Linux 6.6+: O_CREAT|O_DIRECTORY is EINVAL, not EISDIR
                if flags.contains(OpenFlags::O_CREAT) && flags.contains(OpenFlags::O_DIRECTORY) {
                    return Err(EINVAL);
                }
                return Err(EISDIR);
            }
            if open_requests_write(flags) {
                if is_executable_inode_busy(&target) {
                    return Err(ETXTBSY);
                }
                if !has_final_access(&md, FaccessatMode::W_OK, uid, fsgid, &groups) {
                    return Err(EACCES);
                }
            }
            if flags.contains(OpenFlags::O_TRUNC) {
                target.resize(0).map_err(|e| -(e as isize))?;
            }
            vfs::File::new_with_metadata(target, _open_flags_to_vfs_flags(flags), md)
                .map_err(|e| -(e as isize))
        }
        Err(errno) if errno == ENOENT => {
            if !flags.contains(OpenFlags::O_CREAT) || flags.contains(OpenFlags::O_DIRECTORY) {
                return Err(errno);
            }
            let (parent, leaf) = vfs_lookup_parent_for_start(&start, path)?;
            let parent_meta = parent.metadata().map_err(|e| -(e as isize))?;
            check_parent_write_search_access(&parent, uid, fsgid, &groups)?;
            let create_mode = apply_current_umask(mode);

            let setgid = parent_meta.mode.contains(vfs::InodeMode::S_ISGID);
            let child_gid = if setgid { parent_meta.gid } else { fsgid };

            let mut effective_mode = create_mode;
            if effective_mode.contains(vfs::InodeMode::S_ISGID) && uid != 0 && fsgid != child_gid {
                effective_mode.remove(vfs::InodeMode::S_ISGID);
            }

            let inode = parent
                .create_with_attrs(
                    &leaf,
                    FileType::File,
                    vfs::CreateAttrs {
                        mode: effective_mode,
                        uid,
                        gid: child_gid,
                    },
                )
                .map_err(|e| -(e as isize))?;
            vfs::File::new(inode, _open_flags_to_vfs_flags(flags)).map_err(|e| -(e as isize))
        }
        Err(errno) => Err(errno),
    }
}

pub(crate) fn check_memfd_truncate_seals(file: &vfs::File, new_len: usize) -> Result<(), isize> {
    if let Some(seals) = file.memfd_seal_bits() {
        let current_len = file.metadata().map_err(|e| -(e as isize))?.size.max(0) as usize;
        if new_len < current_len && (seals & vfs::F_SEAL_SHRINK) != 0 {
            return Err(EPERM);
        }
        if new_len > current_len && (seals & vfs::F_SEAL_GROW) != 0 {
            return Err(EPERM);
        }
    }
    Ok(())
}

pub(crate) fn open_proc_self_fd(
    path: &str,
    flags: OpenFlags,
) -> Option<Result<Arc<vfs::File>, isize>> {
    let fd_text = path.strip_prefix("/proc/self/fd/")?;
    if fd_text.is_empty() || fd_text.as_bytes().iter().any(|b| !b.is_ascii_digit()) {
        return Some(Err(ENOENT));
    }
    let fd = match fd_text.parse::<usize>() {
        Ok(fd) => fd,
        Err(_) => return Some(Err(ENOENT)),
    };

    let task = current_task().unwrap();
    let (inode, file_type, seals) = {
        let files_ref = task.process.files();
        let fd_table = files_ref.lock();
        let file = match fd_table.get_file(fd) {
            Ok(file) => file,
            Err(e) => return Some(Err(-(e as isize))),
        };
        (file.inode.clone(), file.file_type(), file.memfd_seals())
    };

    let reopened = match vfs::File::new(inode.clone(), _open_flags_to_vfs_flags(flags)) {
        Ok(file) => file,
        Err(e) => return Some(Err(-(e as isize))),
    };
    let seals = seals?;
    reopened.set_memfd_seals(seals);

    if flags.contains(OpenFlags::O_TRUNC) {
        if file_type == vfs::FileType::Dir {
            return Some(Err(EISDIR));
        }
        if !reopened.flags().is_writable() {
            return Some(Err(EACCES));
        }
        if let Err(errno) = check_memfd_truncate_seals(&reopened, 0) {
            return Some(Err(errno));
        }
        if let Err(e) = inode.resize(0) {
            return Some(Err(-(e as isize)));
        }
    }

    Some(Ok(reopened))
}

#[inline]
pub(crate) fn iov_writable_len_for_read(
    user_iov: &UserIoVec,
    offset: usize,
    want: usize,
) -> Result<usize, isize> {
    let accessible = user_iov.accessible_len_at(offset, want, crate::mm::UserAccess::Write);
    if accessible != 0 {
        return Ok(accessible);
    }
    let ubuf = user_iov.writer_buffer_at(offset, 1)?;
    if ubuf.len() == 0 {
        return Err(EFAULT);
    }
    let accessible = user_iov.accessible_len_at(offset, want, crate::mm::UserAccess::Write);
    Ok(accessible.max(1).min(want))
}

pub(crate) fn read_into_user(file: &vfs::File, token: usize, buf: usize, count: usize) -> isize {
    if count == 0 {
        return match file.read(&mut []) {
            Ok(n) => n as isize,
            Err(e) => -(e as isize),
        };
    }

    if file.inode.supports_user_buffer_io() {
        let chunk_cap = count.min(crate::hal::IO_CHUNK_SIZE);
        let mut total = 0usize;
        while total < count {
            let want = (count - total).min(chunk_cap);

            let user_addr = match buf.checked_add(total) {
                Some(v) => v,
                None => {
                    return if total > 0 {
                        total as isize
                    } else {
                        -(SyscallErr::EFAULT as isize)
                    }
                }
            };
            let t0 = crate::task::perf::perf_memory_io_time_now();
            let (writer, accessible) =
                match UserBufferWriter::new_writable_prefix(token, user_addr as *mut u8, want) {
                    Ok(prefix) => prefix,
                    Err(errno) => return if total > 0 { total as isize } else { errno },
                };
            let mut ubuf = writer.into_user_buffer();
            let t1 = crate::task::perf::perf_memory_io_time_now();

            let n = match file.read_user(&mut ubuf) {
                Ok(n) => n,
                Err(e) => {
                    return if total > 0 {
                        total as isize
                    } else {
                        -(e as isize)
                    }
                }
            };
            let t2 = crate::task::perf::perf_memory_io_time_now();
            crate::task::perf::record_pread_uaccess(t1.wrapping_sub(t0));
            crate::task::perf::record_pread_file(t2.wrapping_sub(t1));
            crate::task::perf::record_pread_total_count();
            if n == 0 {
                break;
            }
            total += n;
            if n < accessible {
                break;
            }
            if let Some(task) = current_task() {
                if crate::task::has_actionable_signal(&task) {
                    break;
                }
            }
        }
        return total as isize;
    }

    // kbuf path for pipe/socket/devfs/procfs — avoids ENOSYS probe overhead
    let chunk_cap = count.min(crate::hal::IO_CHUNK_SIZE);
    let mut kbuf = alloc::vec::Vec::new();
    if kbuf.try_reserve(chunk_cap).is_err() {
        return -(SyscallErr::ENOMEM as isize);
    }
    unsafe {
        kbuf.set_len(chunk_cap);
    }

    let mut total = 0usize;
    while total < count {
        let want = (count - total).min(chunk_cap);
        let user_addr = match buf.checked_add(total) {
            Some(v) => v,
            None => {
                return if total > 0 {
                    total as isize
                } else {
                    -(SyscallErr::EFAULT as isize)
                }
            }
        };
        let (mut writer, accessible) =
            match UserBufferWriter::new_writable_prefix(token, user_addr as *mut u8, want) {
                Ok(prefix) => prefix,
                Err(errno) => return if total > 0 { total as isize } else { errno },
            };

        let n = match file.read(&mut kbuf[..accessible]) {
            Ok(n) => n,
            Err(e) => {
                let ret = -(e as isize);
                return if total > 0 { total as isize } else { ret };
            }
        };
        if n == 0 {
            break;
        }

        let copied = match writer.write_from(&kbuf[..n]) {
            Ok(copied) => copied,
            Err(errno) => return if total > 0 { total as isize } else { errno },
        };

        total += copied;
        if copied < n {
            break;
        }
        if let Some(task) = current_task() {
            if crate::task::has_actionable_signal(&task) {
                break;
            }
        }
    }
    total as isize
}

pub(crate) fn read_zero_into_user(token: usize, buf: usize, count: usize) -> isize {
    if count == 0 {
        return 0;
    }

    let chunk_cap = count.min(crate::hal::IO_CHUNK_SIZE);
    let mut total = 0usize;
    while total < count {
        let want = (count - total).min(chunk_cap);
        let user_addr = match buf.checked_add(total) {
            Some(v) => v,
            None => return if total > 0 { total as isize } else { EFAULT },
        };
        let (writer, accessible) =
            match UserBufferWriter::new_writable_prefix(token, user_addr as *mut u8, want) {
                Ok(prefix) => prefix,
                Err(errno) => return if total > 0 { total as isize } else { errno },
            };
        let mut user_buf = writer.into_user_buffer();
        user_buf.clear();
        total += accessible;

        if let Some(task) = current_task() {
            if crate::task::has_actionable_signal(&task) {
                break;
            }
        }
    }
    total as isize
}

pub(crate) fn pread_into_user(
    file: &vfs::File,
    token: usize,
    buf: usize,
    count: usize,
    offset: usize,
) -> isize {
    if count == 0 {
        return match file.pread(offset, &mut []) {
            Ok(n) => n as isize,
            Err(e) => -(e as isize),
        };
    }

    if file.inode.supports_user_buffer_io() {
        let chunk_cap = count.min(crate::hal::IO_CHUNK_SIZE);
        let mut total = 0usize;
        while total < count {
            let want = (count - total).min(chunk_cap);
            let file_off = match offset.checked_add(total) {
                Some(v) => v,
                None => {
                    return if total > 0 {
                        total as isize
                    } else {
                        -(SyscallErr::EINVAL as isize)
                    }
                }
            };
            let user_addr = match buf.checked_add(total) {
                Some(v) => v,
                None => {
                    return if total > 0 {
                        total as isize
                    } else {
                        -(SyscallErr::EFAULT as isize)
                    }
                }
            };
            let t0 = crate::task::perf::perf_memory_io_time_now();
            let (writer, accessible) =
                match UserBufferWriter::new_writable_prefix(token, user_addr as *mut u8, want) {
                    Ok(prefix) => prefix,
                    Err(errno) => return if total > 0 { total as isize } else { errno },
                };
            let mut ubuf = writer.into_user_buffer();
            let t1 = crate::task::perf::perf_memory_io_time_now();

            let n = match file.pread_user(file_off, &mut ubuf) {
                Ok(n) => n,
                Err(e) => {
                    return if total > 0 {
                        total as isize
                    } else {
                        -(e as isize)
                    }
                }
            };
            let t2 = crate::task::perf::perf_memory_io_time_now();
            crate::task::perf::record_pread_uaccess(t1.wrapping_sub(t0));
            crate::task::perf::record_pread_file(t2.wrapping_sub(t1));
            crate::task::perf::record_pread_total_count();
            if n == 0 {
                break;
            }
            total += n;
            if n < accessible {
                break;
            }
            if let Some(task) = current_task() {
                if crate::task::has_actionable_signal(&task) {
                    break;
                }
            }
        }
        return total as isize;
    }

    let chunk_cap = count.min(crate::hal::IO_CHUNK_SIZE);
    let mut kbuf = alloc::vec::Vec::new();
    if kbuf.try_reserve(chunk_cap).is_err() {
        return -(SyscallErr::ENOMEM as isize);
    }
    unsafe {
        kbuf.set_len(chunk_cap);
    }

    let mut total = 0usize;
    while total < count {
        let want = (count - total).min(chunk_cap);
        let file_off = match offset.checked_add(total) {
            Some(v) => v,
            None => {
                return if total > 0 {
                    total as isize
                } else {
                    -(SyscallErr::EINVAL as isize)
                }
            }
        };
        let user_addr = match buf.checked_add(total) {
            Some(v) => v,
            None => {
                return if total > 0 {
                    total as isize
                } else {
                    -(SyscallErr::EFAULT as isize)
                }
            }
        };
        let (mut writer, accessible) =
            match UserBufferWriter::new_writable_prefix(token, user_addr as *mut u8, want) {
                Ok(prefix) => prefix,
                Err(errno) => return if total > 0 { total as isize } else { errno },
            };

        let n = match file.pread(file_off, &mut kbuf[..accessible]) {
            Ok(n) => n,
            Err(e) => {
                let ret = -(e as isize);
                return if total > 0 { total as isize } else { ret };
            }
        };
        if n == 0 {
            break;
        }

        let copied = match writer.write_from(&kbuf[..n]) {
            Ok(copied) => copied,
            Err(errno) => return if total > 0 { total as isize } else { errno },
        };

        total += copied;
        if copied < n {
            break;
        }
        if let Some(task) = current_task() {
            if crate::task::has_actionable_signal(&task) {
                break;
            }
        }
    }
    total as isize
}

pub(crate) fn write_from_user(file: &vfs::File, token: usize, buf: usize, count: usize) -> isize {
    if count == 0 {
        return match file.write(&[]) {
            Ok(n) => n as isize,
            Err(e) => -(e as isize),
        };
    }

    // Fast path for /dev/null, /dev/zero — skip UserBuffer construction
    if file.inode.is_discard_write() {
        return match file.write_discard(count) {
            Ok(n) => n as isize,
            Err(e) => -(e as isize),
        };
    }

    if file.inode.supports_user_buffer_io() {
        let chunk_cap = count.min(crate::hal::IO_CHUNK_SIZE);
        let mut total = 0usize;
        while total < count {
            let want = (count - total).min(chunk_cap);
            let user_addr = match buf.checked_add(total) {
                Some(v) => v,
                None => {
                    return if total > 0 {
                        total as isize
                    } else {
                        -(SyscallErr::EFAULT as isize)
                    }
                }
            };

            // Foreground split bucket (b): uaccess/PTE translation of the user
            // buffer (accessible_len + UserBufferReader construction). Bucket
            // (c+d+e) is the following file.write_user call. perf_diag only.
            let t0 = crate::task::perf::perf_memory_io_time_now();
            let mut accessible = crate::mm::user_accessible_len(
                token,
                user_addr as *const u8,
                want,
                crate::mm::UserAccess::Read,
            );
            if accessible == 0 {
                if total > 0 {
                    return total as isize;
                }
                accessible = want.min(crate::config::PAGE_SIZE);
            }

            let ubuf = match UserBufferReader::new(token, user_addr as *const u8, accessible) {
                Ok(r) => r.into_user_buffer(),
                Err(errno) => return if total > 0 { total as isize } else { errno },
            };
            let t1 = crate::task::perf::perf_memory_io_time_now();

            let n = match file.write_user(&ubuf) {
                Ok(n) => n,
                Err(e) => {
                    return if total > 0 {
                        total as isize
                    } else {
                        -(e as isize)
                    }
                }
            };
            let t2 = crate::task::perf::perf_memory_io_time_now();
            crate::task::perf::record_write_uaccess(t1.wrapping_sub(t0));
            crate::task::perf::record_write_file(t2.wrapping_sub(t1));
            crate::task::perf::record_write_total_count();
            total += n;
            if n == 0 || n < accessible {
                break;
            }
            if let Some(task) = current_task() {
                if crate::task::has_actionable_signal(&task) {
                    break;
                }
            }
        }
        return total as isize;
    }

    let chunk_cap = count.min(crate::hal::IO_CHUNK_SIZE);
    let mut kbuf = alloc::vec::Vec::new();
    if kbuf.try_reserve(chunk_cap).is_err() {
        return -(SyscallErr::ENOMEM as isize);
    }
    unsafe {
        kbuf.set_len(chunk_cap);
    }

    let mut total = 0usize;
    while total < count {
        let want = (count - total).min(chunk_cap);
        let user_addr = match buf.checked_add(total) {
            Some(v) => v,
            None => {
                return if total > 0 {
                    total as isize
                } else {
                    -(SyscallErr::EFAULT as isize)
                }
            }
        };

        let mut accessible = crate::mm::user_accessible_len(
            token,
            user_addr as *const u8,
            want,
            crate::mm::UserAccess::Read,
        );
        if accessible == 0 {
            if total > 0 {
                return total as isize;
            }
            accessible = want.min(crate::config::PAGE_SIZE);
        }

        let reader = match UserBufferReader::new(token, user_addr as *const u8, accessible) {
            Ok(r) => r,
            Err(errno) => return if total > 0 { total as isize } else { errno },
        };
        let copied = match reader.read_into(&mut kbuf[..accessible]) {
            Ok(n) => n,
            Err(errno) => return if total > 0 { total as isize } else { errno },
        };

        let n = match file.write(&kbuf[..copied]) {
            Ok(n) => n,
            Err(e) => {
                let ret = -(e as isize);
                return if total > 0 { total as isize } else { ret };
            }
        };
        total += n;
        if n == 0 || n < copied {
            break;
        }
        if let Some(task) = current_task() {
            if crate::task::has_actionable_signal(&task) {
                break;
            }
        }
    }
    total as isize
}

pub(crate) fn pwrite_from_user(
    file: &vfs::File,
    token: usize,
    buf: usize,
    count: usize,
    offset: usize,
) -> isize {
    if count == 0 {
        return 0_isize;
    }

    if file.inode.supports_user_buffer_io() {
        let chunk_cap = count.min(crate::hal::IO_CHUNK_SIZE);
        let mut total = 0usize;
        while total < count {
            let want = (count - total).min(chunk_cap);
            let file_off = match offset.checked_add(total) {
                Some(v) => v,
                None => {
                    return if total > 0 {
                        total as isize
                    } else {
                        -(SyscallErr::EINVAL as isize)
                    }
                }
            };
            let user_addr = match buf.checked_add(total) {
                Some(v) => v,
                None => {
                    return if total > 0 {
                        total as isize
                    } else {
                        -(SyscallErr::EFAULT as isize)
                    }
                }
            };

            let mut accessible = crate::mm::user_accessible_len(
                token,
                user_addr as *const u8,
                want,
                crate::mm::UserAccess::Read,
            );
            if accessible == 0 {
                if total > 0 {
                    return total as isize;
                }
                accessible = want.min(crate::config::PAGE_SIZE);
            }

            let t0 = crate::task::perf::perf_memory_io_time_now();
            let ubuf = match UserBufferReader::new(token, user_addr as *const u8, accessible) {
                Ok(r) => r.into_user_buffer(),
                Err(errno) => return if total > 0 { total as isize } else { errno },
            };
            let t1 = crate::task::perf::perf_memory_io_time_now();

            let n = match file.pwrite_user(file_off, &ubuf) {
                Ok(n) => n,
                Err(e) => {
                    return if total > 0 {
                        total as isize
                    } else {
                        -(e as isize)
                    }
                }
            };
            let t2 = crate::task::perf::perf_memory_io_time_now();
            crate::task::perf::record_pwrite_uaccess(t1.wrapping_sub(t0));
            crate::task::perf::record_pwrite_file(t2.wrapping_sub(t1));
            crate::task::perf::record_pwrite_total_count();
            total += n;
            if n == 0 || n < accessible {
                break;
            }
            if let Some(task) = current_task() {
                if crate::task::has_actionable_signal(&task) {
                    break;
                }
            }
        }
        return total as isize;
    }

    let chunk_cap = count.min(crate::hal::IO_CHUNK_SIZE);
    let mut kbuf = alloc::vec::Vec::new();
    if kbuf.try_reserve(chunk_cap).is_err() {
        return -(SyscallErr::ENOMEM as isize);
    }
    unsafe {
        kbuf.set_len(chunk_cap);
    }

    let mut total = 0usize;
    while total < count {
        let want = (count - total).min(chunk_cap);
        let file_off = match offset.checked_add(total) {
            Some(v) => v,
            None => {
                return if total > 0 {
                    total as isize
                } else {
                    -(SyscallErr::EINVAL as isize)
                }
            }
        };
        let user_addr = match buf.checked_add(total) {
            Some(v) => v,
            None => {
                return if total > 0 {
                    total as isize
                } else {
                    -(SyscallErr::EFAULT as isize)
                }
            }
        };

        let mut accessible = crate::mm::user_accessible_len(
            token,
            user_addr as *const u8,
            want,
            crate::mm::UserAccess::Read,
        );
        if accessible == 0 {
            if total > 0 {
                return total as isize;
            }
            accessible = want.min(crate::config::PAGE_SIZE);
        }

        let t0 = crate::task::perf::perf_memory_io_time_now();
        let reader = match UserBufferReader::new(token, user_addr as *const u8, accessible) {
            Ok(r) => r,
            Err(errno) => return if total > 0 { total as isize } else { errno },
        };
        let copied = match reader.read_into(&mut kbuf[..accessible]) {
            Ok(n) => n,
            Err(errno) => return if total > 0 { total as isize } else { errno },
        };
        let t1 = crate::task::perf::perf_memory_io_time_now();

        let n = match file.pwrite(file_off, &kbuf[..copied]) {
            Ok(n) => n,
            Err(e) => {
                let ret = -(e as isize);
                return if total > 0 { total as isize } else { ret };
            }
        };
        let t2 = crate::task::perf::perf_memory_io_time_now();
        crate::task::perf::record_pwrite_uaccess(t1.wrapping_sub(t0));
        crate::task::perf::record_pwrite_file(t2.wrapping_sub(t1));
        crate::task::perf::record_pwrite_total_count();
        total += n;
        if n == 0 || n < copied {
            break;
        }
        if let Some(task) = current_task() {
            if crate::task::has_actionable_signal(&task) {
                break;
            }
        }
    }
    total as isize
}

pub(crate) fn write_start_offset(file: &vfs::File) -> usize {
    if file.flags().contains(FileFlags::O_APPEND) {
        if let Ok(metadata) = file.metadata() {
            if metadata.size > 0 {
                return metadata.size as usize;
            }
        }
    }
    file.offset()
}

pub(crate) fn pwrite_start_offset(file: &vfs::File, offset: usize) -> usize {
    if file.flags().contains(FileFlags::O_APPEND) {
        if let Ok(metadata) = file.metadata() {
            if metadata.size > 0 {
                return metadata.size as usize;
            }
        }
    }
    offset
}

pub(crate) fn raise_sigxfsz() {
    if let Some(task) = current_task() {
        {
            task.acquire_inner_lock().add_signal(Signals::SIGXFSZ);
        }
        task.process.notify_signal_waiters();
    }
}

pub(crate) fn apply_fsize_limit(
    file: &vfs::File,
    count: usize,
    offset: usize,
    fsize_limit: usize,
) -> Result<usize, isize> {
    if count == 0 || file.file_type() != FileType::File || fsize_limit == usize::MAX {
        return Ok(count);
    }
    if offset >= fsize_limit {
        raise_sigxfsz();
        return Err(EFBIG);
    }
    Ok(count.min(fsize_limit - offset))
}

pub(crate) fn splice_read_stream(
    file: &vfs::File,
    buf: &mut [u8],
    nonblock: bool,
) -> Result<usize, isize> {
    let mut read_once = || match file.read(buf) {
        Ok(n) => n as isize,
        Err(e) => -(e as isize),
    };
    let ret = if nonblock {
        read_once()
    } else if let Some(wq) = file.inode.read_wait_queue() {
        match WaitQueue::wait_until_interruptible(wq, || {
            let ret = read_once();
            if ret == -(SyscallErr::EAGAIN as isize) {
                None
            } else {
                Some(ret)
            }
        }) {
            WaitResult::Ready(n) => {
                if n < 0 {
                    pass_pipe_reader_baton(file);
                }
                n
            }
            WaitResult::Interrupted => {
                pass_pipe_reader_baton(file);
                -(SyscallErr::ERESTART as isize)
            }
            WaitResult::TimedOut => {
                pass_pipe_reader_baton(file);
                -(SyscallErr::EAGAIN as isize)
            }
        }
    } else {
        read_once()
    };
    if ret < 0 {
        Err(ret)
    } else {
        Ok(ret as usize)
    }
}

pub(crate) fn splice_write_stream(
    file: &vfs::File,
    buf: &[u8],
    nonblock: bool,
) -> Result<usize, isize> {
    let mut write_once = || match file.write(buf) {
        Ok(n) => n as isize,
        Err(e) => -(e as isize),
    };
    let ret = if nonblock {
        write_once()
    } else if let Some(wq) = file.inode.write_wait_queue() {
        match WaitQueue::wait_until_interruptible(wq, || {
            let ret = write_once();
            if ret == -(SyscallErr::EAGAIN as isize) {
                None
            } else {
                Some(ret)
            }
        }) {
            WaitResult::Ready(n) => {
                if n < 0 {
                    pass_pipe_writer_baton(file);
                }
                n
            }
            WaitResult::Interrupted => {
                pass_pipe_writer_baton(file);
                -(SyscallErr::ERESTART as isize)
            }
            WaitResult::TimedOut => {
                pass_pipe_writer_baton(file);
                -(SyscallErr::EAGAIN as isize)
            }
        }
    } else {
        write_once()
    };
    if ret < 0 {
        Err(ret)
    } else {
        Ok(ret as usize)
    }
}

fn pass_pipe_reader_baton(file: &vfs::File) {
    if let Some(pipe) = file.inode.as_any_ref().downcast_ref::<Pipe>() {
        pipe.pass_reader_baton_if_data();
    }
}

fn pass_pipe_writer_baton(file: &vfs::File) {
    if let Some(pipe) = file.inode.as_any_ref().downcast_ref::<Pipe>() {
        pipe.pass_writer_baton_if_space();
    }
}

/// # Warning
/// `fs` & `files` is locked in this function
pub(crate) fn __openat(dirfd: usize, path: &str) -> Result<Arc<vfs::File>, isize> {
    open_file_at(dirfd, path, OpenFlags::O_RDONLY, vfs::InodeMode::S_IRWXUGO)
}

pub(crate) fn split_offset64(offset_low: usize, offset_high: usize) -> usize {
    (offset_low & 0xffff_ffff) | ((offset_high & 0xffff_ffff) << 32)
}

pub(crate) const SPLICE_F_MOVE: u32 = 0x01;
pub(crate) const SPLICE_F_NONBLOCK: u32 = 0x02;
pub(crate) const SPLICE_F_MORE: u32 = 0x04;
pub(crate) const SPLICE_F_GIFT: u32 = 0x08;
pub(crate) const SPLICE_VALID_FLAGS: u32 =
    SPLICE_F_MOVE | SPLICE_F_NONBLOCK | SPLICE_F_MORE | SPLICE_F_GIFT;
pub(crate) const VMSPLICE_VALID_FLAGS: u32 = SPLICE_VALID_FLAGS;

/// Check if two File objects refer to the same underlying pipe.
///
/// Compares the shared `PipeRingBuffer` Arc (the backing storage) rather than
/// the inode Arc, because paired pipefd[0] (read end) and pipefd[1] (write end)
/// have different inode Arcs but share the same buffer.  splice/tee must reject
/// same-pipe operations where source and destination are the same pipe.
pub(crate) fn is_same_pipe(f1: &vfs::File, f2: &vfs::File) -> bool {
    if f1.file_type() != FileType::Pipe || f2.file_type() != FileType::Pipe {
        return false;
    }
    // Compare the shared pipe ring buffer — the definitive same-pipe identity.
    // pipefd[0] and pipefd[1] share one PipeRingBuffer even though each endpoint
    // has its own Pipe (inode) struct.
    use crate::fs::dev::pipe::Pipe;
    let p1 = match f1.inode.as_any_ref().downcast_ref::<Pipe>() {
        Some(p) => p,
        None => return false,
    };
    let p2 = match f2.inode.as_any_ref().downcast_ref::<Pipe>() {
        Some(p) => p,
        None => return false,
    };
    Arc::ptr_eq(p1.buffer_arc(), p2.buffer_arc())
}

/// If offset is not NULL, then it points to a variable holding the
/// file offset from which sendfile() will start reading data from
/// in_fd.
///
/// When sendfile() returns,
/// this variable will be set to the offset of the byte following
/// the last byte that was read.
///
/// If offset is not NULL, then sendfile() does not modify the file
/// offset of in_fd; otherwise the file offset is adjusted to reflect
/// the number of bytes read from in_fd.
///
/// If offset is NULL, then data will be read from in_fd starting at
/// the file offset, and the file offset will be updated by the call.
/// Read an optional file offset from user memory. Returns EINVAL for negative values.
pub(crate) fn read_user_off(ptr: *mut usize, token: usize) -> Result<Option<usize>, isize> {
    if ptr.is_null() {
        return Ok(None);
    }
    let v: usize = match UserPtrMut::new(ptr).read(token) {
        Ok(v) => v,
        Err(errno) => return Err(errno),
    };
    // off_t is signed; reject negative offsets (top bit set in usize repr)
    if v > isize::MAX as usize {
        return Err(EINVAL);
    }
    Ok(Some(v))
}

bitflags! {
    pub struct FstatatFlags: u32 {
        const AT_EMPTY_PATH = 0x1000;
        const AT_NO_AUTOMOUNT = 0x800;
        const AT_SYMLINK_NOFOLLOW = 0x100;
    }
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct Statfs {
    /// Type of filesystem
    f_type: usize,
    /// Optimal transfer block size
    f_bsize: usize,
    /// Total data blocks in filesystem
    f_blocks: u64,
    /// Free blocks in filesystem
    f_bfree: u64,
    /// Free blocks available to
    /// unprivileged user
    f_bavail: u64,
    /// Total file nodes in filesystem
    f_files: u64,
    /// Free file nodes in filesystem
    f_ffree: u64,
    /// Filesystem ID
    f_fsid: [i32; 2],
    /// Maximum length of filenames
    f_namelen: usize,
    /// Fragment size (since Linux 2.6)
    f_frsize: usize,
    /// Mount flags of filesystem
    f_flag: usize,
    /// Padding bytes reserved for future use
    f_spare: [usize; 4],
}
pub(crate) fn superblock_to_statfs(sb: &SuperBlock) -> Statfs {
    Statfs {
        f_type: sb.f_type as usize,
        f_bsize: sb.f_bsize as usize,
        f_blocks: sb.f_blocks,
        f_bfree: sb.f_bfree,
        f_bavail: sb.f_bavail,
        f_files: sb.f_files,
        f_ffree: sb.f_ffree,
        f_fsid: sb.f_fsid,
        f_namelen: sb.f_namelen as usize,
        f_frsize: sb.f_frsize as usize,
        f_flag: sb.flags as usize,
        f_spare: [0; 4],
    }
}

pub(crate) fn write_statfs(buf: *mut Statfs, statfs: &Statfs) -> isize {
    let token = current_task().unwrap().get_user_token();
    if UserPtrMut::new(buf).write(token, statfs).is_err() {
        log::error!("[sys_statfs] Failed to copy to {:?}", buf);
        return EFAULT;
    };
    SUCCESS
}

pub(crate) fn caller_ids_and_groups() -> (u32, u32, Vec<u32>) {
    let task = current_task().unwrap();
    let inner = task.acquire_inner_lock();
    (inner.fsuid, inner.fsgid, inner.groups.to_vec())
}

pub(crate) fn do_fchmod(inode: &Arc<dyn vfs::IndexNode>, mode: u32) -> Result<(), isize> {
    let mut meta = match inode.metadata() {
        Ok(m) => m,
        Err(e) => return Err(-(e as isize)),
    };
    let (uid, fsgid, groups) = caller_ids_and_groups();

    // Only owner or root can chmod
    if uid != 0 && uid != meta.uid {
        return Err(EPERM);
    }

    let old_gid = meta.gid;
    let perms = vfs::InodeMode::from_bits_truncate(mode) & vfs::InodeMode::S_IALLUGO;
    let mut new_mode = (meta.mode & !vfs::InodeMode::S_IALLUGO) | perms;

    // Linux: clear SGID if caller is not root and not in file's group
    // (applies to all file types, including directories)
    if new_mode.contains(vfs::InodeMode::S_ISGID) {
        let in_group = fsgid == old_gid || groups.iter().any(|g| *g == old_gid);
        if uid != 0 && !in_group {
            new_mode.remove(vfs::InodeMode::S_ISGID);
        }
    }

    meta.mode = new_mode;

    inode.set_metadata(&meta).map_err(|e| -(e as isize))
}

bitflags! {
    pub struct FchownatFlags: u32 {
        const AT_SYMLINK_NOFOLLOW = 0x100;
        const AT_NO_AUTOMOUNT = 0x800;
        const AT_EMPTY_PATH = 0x1000;
    }
}

pub(crate) fn do_chown(inode: &Arc<dyn vfs::IndexNode>, owner: u32, group: u32) -> isize {
    const CHOWN_ID_NO_CHANGE: u32 = u32::MAX;
    let mut meta = match inode.metadata() {
        Ok(m) => m,
        Err(e) => return -(e as isize),
    };
    let (fsuid, fsgid, groups) = caller_ids_and_groups();

    let change_uid = owner != CHOWN_ID_NO_CHANGE;
    let change_gid = group != CHOWN_ID_NO_CHANGE;

    if fsuid == 0 {
        if change_uid {
            meta.uid = owner;
        }
        if change_gid {
            meta.gid = group;
        }
    } else {
        if fsuid != meta.uid {
            return EPERM;
        }
        if change_uid && owner != meta.uid {
            return EPERM;
        }
        if change_gid && group != fsgid && !groups.iter().any(|g| *g == group) {
            return EPERM;
        }
        if change_gid {
            meta.gid = group;
        }
    }

    // Clear suid/sgid on ownership change for non-directories
    if (change_uid || change_gid) && meta.file_type != vfs::FileType::Dir {
        meta.mode.remove(vfs::InodeMode::S_ISUID);
        if meta.mode.contains(vfs::InodeMode::S_IXGRP) {
            meta.mode.remove(vfs::InodeMode::S_ISGID);
        }
    }

    match inode.set_metadata(&meta) {
        Ok(()) => SUCCESS,
        Err(e) => -(e as isize),
    }
}

pub(crate) const FIONREAD: u32 = 0x541B;
pub(crate) const FIONBIO: u32 = 0x5421;

bitflags! {
    pub struct UnlinkatFlags: u32 {
        const AT_REMOVEDIR = 0x200;
    }
}

bitflags! {
    pub struct UmountFlags: u32 {
        const MNT_FORCE           =   1;
        const MNT_DETACH          =   2;
        const MNT_EXPIRE          =   4;
        const UMOUNT_NOFOLLOW     =   8;
    }
}

/// Extract the target MountFS from a MountFSInode for umount/detach operations.
/// Returns the child MountFS if the inode is a mountpoint, or the MountFS itself
/// if the inode is a mountpoint root.
pub(crate) fn resolve_umount_target(
    inode: &Arc<dyn vfs::IndexNode>,
) -> Result<Arc<vfs::MountFS>, isize> {
    let mnt_inode = match inode.as_any_ref().downcast_ref::<vfs::MountFSInode>() {
        Some(m) => m,
        None => return Err(EINVAL),
    };
    if mnt_inode.is_mountpoint_root() {
        return Ok(mnt_inode.mount_fs.clone());
    }
    let inode_id = match mnt_inode.inner_inode.metadata() {
        Ok(md) => md.inode_id,
        Err(e) => return Err(-(e as isize)),
    };
    mnt_inode
        .mount_fs
        .mountpoints
        .lock()
        .get(&inode_id)
        .cloned()
        .ok_or(EINVAL)
}

bitflags! {
    pub struct MountFlags: usize {
        const MS_RDONLY         =   1;
        const MS_NOSUID         =   2;
        const MS_NODEV          =   4;
        const MS_NOEXEC         =   8;
        const MS_SYNCHRONOUS    =   16;
        const MS_REMOUNT        =   32;
        const MS_MANDLOCK       =   64;
        const MS_DIRSYNC        =   128;
        const MS_NOSYMFOLLOW    =   0x100;
        const MS_NOATIME        =   1024;
        const MS_NODIRATIME     =   2048;
        const MS_BIND           =   4096;
        const MS_MOVE           =   8192;
        const MS_REC            =   16384;
        const MS_SILENT         =   32768;
        const MS_POSIXACL       =   (1<<16);
        const MS_UNBINDABLE     =   (1<<17);
        const MS_PRIVATE        =   (1<<18);
        const MS_SLAVE          =   (1<<19);
        const MS_SHARED         =   (1<<20);
        const MS_RELATIME       =   (1<<21);
        const MS_KERNMOUNT      =   (1<<22);
        const MS_I_VERSION      =   (1<<23);
        const MS_STRICTATIME    =   (1<<24);
        const MS_LAZYTIME       =   (1<<25);
        const MS_NOREMOTELOCK   =   (1<<27);
        const MS_NOSEC          =   (1<<28);
        const MS_BORN           =   (1<<29);
        const MS_ACTIVE         =   (1<<30);
        const MS_NOUSER         =   (1<<31);
    }
}

/// Bind mount: make source subtree visible at target.
pub(crate) fn do_bind_mount(
    source: *const u8,
    token: usize,
    lookup_inode: &Arc<dyn vfs::IndexNode>,
    lookup_path: &str,
    target_inode: Arc<dyn vfs::IndexNode>,
    mountflags: MountFlags,
) -> Result<Arc<vfs::MountFS>, isize> {
    let source_path_raw = if source.is_null() {
        return Err(EINVAL);
    } else {
        match user_cstring(token, source) {
            Ok(s) => s,
            Err(errno) => return Err(errno),
        }
    };

    let source_inode = match vfs_lookup(lookup_inode, &source_path_raw, true) {
        Ok(inode) => inode,
        Err(errno) => {
            error!(
                "[do_bind_mount] vfs_lookup source '{}' failed: {}",
                source_path_raw, errno
            );
            return Err(errno);
        }
    };

    let source_mfs_inode = match source_inode
        .as_any_ref()
        .downcast_ref::<vfs::MountFSInode>()
    {
        Some(mfs) => mfs,
        None => return Err(EINVAL),
    };
    let source_mount_fs = source_mfs_inode.mount_fs.clone();
    let source_inner: Arc<dyn vfs::IndexNode> = source_mfs_inode.inner_inode.clone();

    // Reject bind mount from unbindable source
    if source_mount_fs.propagation().is_unbindable() {
        warn!(
            "[do_bind_mount] source mount '{}' is unbindable, refusing bind",
            source_path_raw
        );
        return Err(EINVAL);
    }

    // Collect recursive bind snapshot BEFORE creating base mount, so the
    // new mnt_fs doesn't pollute the source mount tree during snapshotting.
    // Skip unbindable submounts — they must not be replicated.
    let rbind_snapshot: Option<Vec<RbindEntry>> = if mountflags.contains(MountFlags::MS_REC) {
        let mut snapshot = collect_rbind_snapshot(source_mount_fs.clone(), source_inner.clone());
        snapshot.retain(|e| !e.child_mfs.propagation().is_unbindable());
        Some(snapshot)
    } else {
        None
    };

    let target_mfs_inode = match target_inode
        .as_any_ref()
        .downcast_ref::<vfs::MountFSInode>()
    {
        Some(mfs) => mfs,
        None => return Err(EINVAL),
    };

    let mnt_flags = {
        // Linux: bind mount inherits source mount's persistent state flags
        // (RDONLY, NOSYMFOLLOW, etc.).  Operation-only flags (BIND, REC,
        // REMOUNT) are not mount state and must not leak into VFS MountFlags.
        let mut flags = source_mount_fs.mount_flags();
        let user_override = (mountflags.bits() as u32)
            & !(MountFlags::MS_BIND.bits() as u32
                | MountFlags::MS_REC.bits() as u32
                | MountFlags::MS_REMOUNT.bits() as u32);
        if user_override != 0 {
            let user_vfs = vfs::MountFlags::from_bits_truncate(user_override);
            let atime_all = vfs::MountFlags::NOATIME
                | vfs::MountFlags::NODIRATIME
                | vfs::MountFlags::RELATIME
                | vfs::MountFlags::STRICTATIME;
            // Separate atime overrides (new request → normalize_request)
            // from non-atime overrides (OR directly into flags).
            if user_vfs.intersects(atime_all) {
                flags = (flags & !atime_all) | vfs::normalize_request(user_vfs);
            }
            flags |= user_vfs & !atime_all;
        }
        // Defensive canonicalize: source should already be canonical, but
        // strip any stale bits just in case (idempotent = safe).
        vfs::canonicalize_state(flags)
    };
    // Use mount_subtree_inner(false) to skip automatic propagation.
    // We'll set up the final propagation group and propagate manually,
    // ensuring peers get the correct group membership.
    let mnt_fs = match target_mfs_inode.mount_subtree_inner(
        source_mount_fs.lifecycle.clone(),
        source_inner,
        mnt_flags,
        Some(alloc::string::String::from(lookup_path)),
        false,
    ) {
        Ok(fs) => fs,
        Err(e) => return Err(-(e as isize)),
    };
    let source_path = if source_path_raw.starts_with('/') {
        source_path_raw
    } else {
        alloc::format!("/{}", source_path_raw)
    };
    mnt_fs.set_mount_source(Some(source_path));

    // Set up propagation matching the source mount.
    // The mount_subtree_inner(false) already inherited the parent's group ID
    // (if parent shared) but did NOT register in PEER_GROUPS.
    // Unconditionally unregister from parent's group, then apply source's propagation.
    let inherited_gid = mnt_fs.propagation().peer_group_id();
    if inherited_gid != 0 {
        vfs::propagation::unregister_peer_mount(&mnt_fs);
    }
    let source_prop = source_mount_fs.propagation();
    let source_is_shared = source_prop.is_shared();
    let source_gid = source_prop.peer_group_id();

    // Compute desired (peer_gid, master_gid) from source + inherited context
    let desired_peer: Option<u32> = if source_is_shared {
        Some(source_gid)
    } else if inherited_gid != 0 {
        // Private source under shared target parent → join target's child group
        Some(inherited_gid)
    } else {
        None
    };
    let desired_master: Option<u32> = if source_prop.is_slave() {
        let mgid = source_prop.master_group_id();
        if mgid != 0 {
            Some(mgid)
        } else {
            None
        }
    } else {
        None
    };

    vfs::propagation::configure_propagation_no_register(&mnt_fs, desired_peer, desired_master);

    // Propagate mount event. The propagation source is the mount that HOLDS
    // the mountpoint. When the target is itself a mount root, the new mount
    // is created inside that existing mount (chain: parent → old → new),
    // so the propagation source must be the existing mount (not its parent).
    // The walk-up heuristic below was incorrect — it switched the source to
    // the grandparent, losing the correct mountpoint inode.
    let (target_parent_mfs, target_ino) = if target_mfs_inode.is_mountpoint_root() {
        // target is an existing mount root → propagate FROM it
        let child_mfs = target_mfs_inode.mount_fs.clone();
        let md = match target_inode.metadata() {
            Ok(md) => md,
            Err(_) => {
                vfs::propagation::unregister_peer_mount(&mnt_fs);
                vfs::propagation::unregister_slave_mount(&mnt_fs);
                mnt_fs.propagation().set_peer_group_id(0);
                mnt_fs.propagation().set_master_group_id(0);
                return Err(-(SyscallErr::EIO as isize));
            }
        };
        (child_mfs, md.inode_id)
    } else {
        let md = match target_inode.metadata() {
            Ok(md) => md,
            Err(_) => {
                vfs::propagation::unregister_peer_mount(&mnt_fs);
                vfs::propagation::unregister_slave_mount(&mnt_fs);
                mnt_fs.propagation().set_peer_group_id(0);
                mnt_fs.propagation().set_master_group_id(0);
                return Err(-(SyscallErr::EIO as isize));
            }
        };
        (target_mfs_inode.mount_fs.clone(), md.inode_id)
    };
    let child_name = lookup_path.rsplit('/').next().unwrap_or("");
    vfs::propagation::propagate_mount(&target_parent_mfs, target_ino, &mnt_fs, child_name);

    // NOW register in peer/slave group AFTER propagation (prevents self-peer loop)
    vfs::propagation::register_current_propagation(&mnt_fs);

    if let Some(snapshot) = rbind_snapshot {
        if let Err(e) =
            apply_rbind_snapshot(&snapshot, source_mount_fs, mnt_fs.clone(), lookup_path)
        {
            let _ = mnt_fs.umount();
            return Err(-(e as isize));
        }
    }

    Ok(mnt_fs)
}

/// Apply an explicit propagation override to a mount and its subtree.
/// Used for combined flags like `mount --bind --make-slave`.
///
/// The mount has already been created by `do_bind_mount()` (which applied
/// source-based propagation, peer registration, and rbind snapshot).
/// This function overrides the final propagation type on top.
pub(crate) fn apply_propagation_change(
    mnt_fs: &Arc<vfs::MountFS>,
    prop_type: vfs::propagation::PropagationType,
    recursive: bool,
) {
    // DragonOS: delegate to set_propagation_type for correct idempotent
    // group handling (Shared→Shared no-op, SharedSlave→Slave keeps master).
    vfs::propagation::set_propagation_type(mnt_fs, prop_type);
    if recursive {
        set_propagation_recursive(mnt_fs, prop_type);
    }
}

/// Entry in rbind snapshot: records everything needed to recreate a submount
/// in the target tree without relying on name-based find().
pub(crate) struct RbindEntry {
    child_mfs: Arc<vfs::MountFS>,
    source_parent_mfs: Arc<vfs::MountFS>,
    child_name: alloc::string::String,
    mountpoint_id: usize,
}

/// Collect all submounts under `source_subtree_root` within `source_mfs` tree.
///
/// Returns Vec of (child_mfs, parent_mfs, relative_name) — BFS order,
/// no mutations to the mount tree.
pub(crate) fn collect_rbind_snapshot(
    source_mfs: Arc<vfs::MountFS>,
    source_subtree_root: Arc<dyn vfs::IndexNode>,
) -> Vec<RbindEntry> {
    let _start = crate::task::perf::perf_time_now();
    const MAX_DEPTH: usize = 256;

    let mut queue: VecDeque<(Arc<vfs::MountFS>, Arc<dyn vfs::IndexNode>)> = VecDeque::new();
    let mut result: Vec<RbindEntry> = Vec::new();
    let mut seen: Vec<usize> = Vec::new();
    let root_ptr = Arc::as_ptr(&source_mfs) as usize;
    seen.push(root_ptr);

    // Seed: submounts directly reachable from source_subtree_root
    {
        let entries: Vec<(usize, Arc<vfs::MountFS>)> = {
            let mps = source_mfs.mountpoints.lock();
            mps.iter().map(|(k, v)| (*k, v.clone())).collect()
        };
        for (ino, child_mfs) in &entries {
            let ptr = Arc::as_ptr(child_mfs) as usize;
            // Linear scan cost: seen.len()
            crate::fs::vfs::mount::counters::RBIND_SEEN_SCAN
                .fetch_add(seen.len(), Ordering::Relaxed);
            if seen.contains(&ptr) {
                continue;
            }
            // list_dirents call
            crate::fs::vfs::mount::counters::RBIND_DIRENT_CALLS.fetch_add(1, Ordering::Relaxed);
            if let Ok(dirents) = source_subtree_root.list_dirents() {
                if let Some((name, _, _)) = dirents.iter().find(|(_, i, _)| *i == *ino) {
                    seen.push(ptr);
                    queue.push_back((child_mfs.clone(), child_mfs.mountpoint_root_inode()));
                    result.push(RbindEntry {
                        child_mfs: child_mfs.clone(),
                        source_parent_mfs: source_mfs.clone(),
                        child_name: name.clone(),
                        mountpoint_id: *ino,
                    });
                }
            }
        }
    }

    // BFS: for each child, collect its submounts (with cycle detection + depth limit)
    while let Some((child_mfs, child_root)) = queue.pop_front() {
        if seen.len() > MAX_DEPTH {
            log::error!("[collect_rbind_snapshot] max depth {} exceeded", MAX_DEPTH);
            break;
        }
        let mps = child_mfs.mountpoints.lock();
        for (&grand_ino, grandchild) in mps.iter() {
            let ptr = Arc::as_ptr(grandchild) as usize;
            // Linear scan cost: seen.len()
            crate::fs::vfs::mount::counters::RBIND_SEEN_SCAN
                .fetch_add(seen.len(), Ordering::Relaxed);
            if seen.contains(&ptr) {
                continue;
            }
            seen.push(ptr);
            if let Some(ref child_mfs_inode) =
                child_root.as_any_ref().downcast_ref::<vfs::MountFSInode>()
            {
                // list_dirents call
                crate::fs::vfs::mount::counters::RBIND_DIRENT_CALLS.fetch_add(1, Ordering::Relaxed);
                if let Ok(dirents) = child_mfs_inode.inner_inode.list_dirents() {
                    if let Some((name, _, _)) = dirents.iter().find(|(_, i, _)| *i == grand_ino) {
                        result.push(RbindEntry {
                            child_mfs: grandchild.clone(),
                            source_parent_mfs: child_mfs.clone(),
                            child_name: name.clone(),
                            mountpoint_id: grand_ino,
                        });
                        queue.push_back((grandchild.clone(), grandchild.mountpoint_root_inode()));
                    }
                }
            }
        }
    }

    let elapsed = crate::task::perf::perf_time_now().wrapping_sub(_start);
    crate::fs::vfs::mount::counters::RBIND_SNAPSHOT_CALLS.fetch_add(1, Ordering::Relaxed);
    crate::fs::vfs::mount::counters::RBIND_SNAPSHOT_CYCLES.fetch_add(elapsed, Ordering::Relaxed);
    crate::fs::vfs::mount::counters::RBIND_SNAPSHOT_ENTRIES
        .fetch_add(result.len(), Ordering::Relaxed);
    result
}

/// Recursively apply a propagation type change to all child mounts.
///
/// Uses snapshot-first BFS to avoid mutating the mount tree while iterating.
pub(crate) fn set_propagation_recursive(
    root: &Arc<vfs::MountFS>,
    prop_type: vfs::propagation::PropagationType,
) {
    // Snapshot all child mounts (BFS order)
    let mut children: Vec<Arc<vfs::MountFS>> = Vec::new();
    let mut queue: Vec<Arc<vfs::MountFS>> = {
        let mps = root.mountpoints.lock();
        mps.values().cloned().collect()
    };
    while let Some(child) = queue.pop() {
        children.push(child.clone());
        let mps = child.mountpoints.lock();
        for grandchild in mps.values() {
            queue.push(grandchild.clone());
        }
    }

    // Apply propagation change to each child (no locks held during iteration)
    for child in &children {
        let master_gid = if prop_type == vfs::propagation::PropagationType::Slave {
            let parent_prop = child.propagation();
            parent_prop.peer_group_id()
        } else {
            0
        };

        if prop_type == vfs::propagation::PropagationType::Slave && master_gid != 0 {
            child.propagation().set_master_group_id(master_gid);
        }
        vfs::propagation::set_propagation_type(child, prop_type);
        // registration handled inside set_propagation_type now
    }
}

/// Apply previously collected rbind snapshot to the target mount tree.
///
/// Uses source→target parent mapping (by Arc pointer) to locate the correct
/// target parent for each submount. All-or-nothing: any failure rolls back
/// all created mounts.
pub(crate) fn apply_rbind_snapshot(
    snapshot: &[RbindEntry],
    source_mfs: Arc<vfs::MountFS>,
    target_mfs: Arc<vfs::MountFS>,
    _target_base_path: &str,
) -> Result<(), SyscallErr> {
    let mut mnt_map: BTreeMap<usize, Arc<vfs::MountFS>> = BTreeMap::new();
    mnt_map.insert(Arc::as_ptr(&source_mfs) as usize, target_mfs.clone());

    let mut created: Vec<Arc<vfs::MountFS>> = Vec::new();

    for entry in snapshot {
        let source_parent_ptr = Arc::as_ptr(&entry.source_parent_mfs) as usize;
        let target_parent = match mnt_map.get(&source_parent_ptr) {
            Some(p) => p.clone(),
            None => {
                rollback_mounts(&created);
                return Err(SyscallErr::EINVAL);
            }
        };

        // DragonOS: use source child's self_mountpoint inner_inode to
        // construct backref in target tree — no find(child_name) needed.
        let covered_inode = entry
            .child_mfs
            .self_mountpoint()
            .map(|mp| mp.inner_inode.clone())
            .unwrap_or_else(|| entry.child_mfs.root_inner_inode());
        let target_mfs_inode = vfs::MountFSInode::new(covered_inode, target_parent.clone());

        let mount_path = match target_parent.mount_path() {
            Some(ref p) => alloc::format!("{}/{}", p, entry.child_name),
            None => alloc::format!("/{}", entry.child_name),
        };

        match target_mfs_inode.mount_subtree_inner(
            entry.child_mfs.lifecycle.clone(),
            entry.child_mfs.root_inner_inode(),
            // Canonicalize: stored flags should already be clean, but strip
            // any stale STRICTATIME just in case (idempotent = safe).
            vfs::canonicalize_state(entry.child_mfs.mount_flags()),
            Some(mount_path),
            false,
        ) {
            Ok(new_mnt) => {
                let child_prop = entry.child_mfs.propagation();
                let child_peer = if child_prop.is_shared() {
                    Some(child_prop.peer_group_id())
                } else {
                    None
                };
                let child_master = if child_prop.is_slave() {
                    Some(child_prop.master_group_id())
                } else {
                    None
                };
                vfs::propagation::install_propagation(&new_mnt, child_peer, child_master);
                if child_prop.is_unbindable() {
                    new_mnt
                        .propagation()
                        .set_prop_type_value(vfs::propagation::PropagationType::Unbindable);
                }
                if let Some(src) = entry.child_mfs.mount_source() {
                    new_mnt.set_mount_source(Some(src));
                }
                let child_ptr = Arc::as_ptr(&entry.child_mfs) as usize;
                mnt_map.insert(child_ptr, new_mnt.clone());
                created.push(new_mnt);
            }
            Err(e) => {
                rollback_mounts(&created);
                return Err(e);
            }
        }
    }
    Ok(())
}

/// Check whether any mount in the subtree rooted at `root_mfs` has
/// unbindable propagation. Uses BFS with snapshot to avoid deadlocks.
/// Conservative: returns true on overflow / errors.
pub(crate) fn subtree_has_unbindable(root_mfs: &Arc<vfs::MountFS>) -> bool {
    const MAX_NODES: usize = 256;
    if root_mfs.propagation().is_unbindable() {
        return true;
    }
    let mut queue: Vec<Arc<vfs::MountFS>> = {
        let mps = root_mfs.mountpoints.lock();
        mps.values().cloned().collect()
    };
    let mut checked: usize = 0;
    while let Some(child) = queue.pop() {
        if child.propagation().is_unbindable() {
            return true;
        }
        checked += 1;
        if checked > MAX_NODES {
            return true;
        }
        let mps = child.mountpoints.lock();
        for grandchild in mps.values() {
            queue.push(grandchild.clone());
        }
    }
    false
}

pub(crate) fn rollback_mounts(created: &[Arc<vfs::MountFS>]) {
    for mnt in created.iter().rev() {
        let _ = mnt.umount();
    }
}

bitflags! {
    pub struct UtimensatFlags: u32 {
        const AT_SYMLINK_NOFOLLOW = 0x100;
    }
}

pub(crate) fn record_flock_close(releases: &mut Vec<(usize, usize, usize)>, file: &Arc<vfs::File>) {
    let description = file.description_id();
    let ref_count = Arc::strong_count(file);
    if let Some((_, closed, refs)) = releases
        .iter_mut()
        .find(|(existing, _, _)| *existing == description)
    {
        *closed += 1;
        *refs = ref_count;
    } else {
        releases.push((description, 1, ref_count));
    }
}

pub(crate) fn release_closed_flock_descriptions(releases: Vec<(usize, usize, usize)>) {
    let mut locks = FLOCK_LOCKS.lock();
    for (description, closed, refs) in releases {
        if closed >= refs {
            locks.retain(|lock| lock.owner_description != description);
        }
    }
}

pub(crate) fn release_flock_description(description: usize) {
    FLOCK_LOCKS
        .lock()
        .retain(|lock| lock.owner_description != description);
}

/// Release all flock locks owned by the given file description.
///
/// Called when the last fd referencing a file description is closed
/// (e.g., from `close_files_on_exit` or direct close).
pub fn release_flocks_for_description(desc_id: usize) {
    FLOCK_LOCKS
        .lock()
        .retain(|lock| lock.owner_description != desc_id);
}

pub fn release_flock_for_file_if_last(file: &Arc<vfs::File>) {
    let mut releases = Vec::new();
    record_flock_close(&mut releases, file);
    release_closed_flock_descriptions(releases);
}

// ── POSIX lock thin wrappers ──────────────────────────────────────────

pub(crate) fn fcntl_getlk(file: &vfs::File, arg: usize, _owner_pid: usize) -> isize {
    let token = current_user_token();
    let mut flock = match UserPtrMut::<PosixFlock>::from_addr(arg).read(token) {
        Ok(f) => f,
        Err(_) => return EFAULT,
    };
    let task = current_task().unwrap();
    let files = task.process.files();
    let ft = files.lock();
    let owner_id = ft.lock_owner_id();
    let owner_pid = task.pid() as i32;
    drop(ft);
    let owner = LockOwner::Posix {
        owner_id,
        owner_pid,
    };
    match posix_lock_get(file, owner, &mut flock) {
        Ok(()) => match UserPtrMut::<PosixFlock>::from_addr(arg).write(token, &flock) {
            Ok(()) => SUCCESS,
            Err(_) => EFAULT,
        },
        Err(e) => -(e as isize),
    }
}

pub(crate) fn fcntl_getlk_ofd(file: &vfs::File, arg: usize) -> isize {
    let token = current_user_token();
    let mut flock = match UserPtrMut::<PosixFlock>::from_addr(arg).read(token) {
        Ok(f) => f,
        Err(_) => return EFAULT,
    };
    let owner = LockOwner::Ofd {
        open_file_id: file.open_file_id(),
    };
    match posix_lock_get(file, owner, &mut flock) {
        Ok(()) => match UserPtrMut::<PosixFlock>::from_addr(arg).write(token, &flock) {
            Ok(()) => SUCCESS,
            Err(_) => EFAULT,
        },
        Err(e) => -(e as isize),
    }
}

pub(crate) fn fcntl_setlk(file: &vfs::File, arg: usize, _owner_pid: usize, wait: bool) -> isize {
    let token = current_user_token();
    let flock = match UserPtr::<PosixFlock>::from_addr(arg).read(token) {
        Ok(f) => f,
        Err(_) => return EFAULT,
    };
    let task = current_task().unwrap();
    let files = task.process.files();
    let ft = files.lock();
    let owner_id = ft.lock_owner_id();
    drop(ft);
    let owner_pid = task.pid() as i32;
    let owner = LockOwner::Posix {
        owner_id,
        owner_pid,
    };
    match posix_lock_set(file, owner, &flock, wait) {
        Ok(()) => SUCCESS,
        Err(e) => -(e as isize),
    }
}

pub(crate) fn fcntl_setlk_ofd(file: &vfs::File, arg: usize, wait: bool) -> isize {
    let token = current_user_token();
    let flock = match UserPtr::<PosixFlock>::from_addr(arg).read(token) {
        Ok(f) => f,
        Err(_) => return EFAULT,
    };
    // Linux requires l_pid == 0 for OFD locks
    if flock.l_pid != 0 {
        return -(SyscallErr::EINVAL as isize);
    }
    let owner = LockOwner::Ofd {
        open_file_id: file.open_file_id(),
    };
    match posix_lock_set(file, owner, &flock, wait) {
        Ok(()) => SUCCESS,
        Err(e) => -(e as isize),
    }
}

pub fn release_fcntl_locks_for_pid(_pid: usize) {
    // Per-file release handled by drop_fd; full shard scan deferred to Phase 4.
}

pub(crate) fn release_fcntl_locks_for_pid_key(_pid: usize, _key: LockKey) {
    // Per-file release handled by drop_fd.
}

pub fn close_cloexec_and_release_fcntl_locks(pid: usize, fd_table: &mut vfs::FdTable) {
    let mut flock_releases = Vec::new();
    for fd in 0..fd_table.len() {
        if fd_table.get_cloexec(fd) {
            if let Ok(file) = fd_table.get_file(fd) {
                let owner_id = fd_table.lock_owner_id();
                release_posix_for_owner(&file, owner_id);
                record_flock_close(&mut flock_releases, &file);
            }
        }
    }
    fd_table.close_cloexec();
    release_closed_flock_descriptions(flock_releases);
}

bitflags! {
    pub struct FaccessatMode: u32 {
        const F_OK = 0;
        const R_OK = 4;
        const W_OK = 2;
        const X_OK = 1;
    }
    pub struct FaccessatFlags: u32 {
        const AT_SYMLINK_NOFOLLOW = 0x100;
        const AT_EACCESS = 0x200;
    }
}

pub(crate) fn access_subject_ids(use_effective: bool) -> (u32, u32) {
    let task = current_task().unwrap();
    let inner = task.acquire_inner_lock();
    if use_effective {
        (inner.euid, inner.egid)
    } else {
        (inner.uid, inner.gid)
    }
}

pub(crate) fn access_subject_ids_and_groups(use_effective: bool) -> (u32, u32, Vec<u32>) {
    let task = current_task().unwrap();
    let inner = task.acquire_inner_lock();
    let groups = inner.groups.to_vec();
    if use_effective {
        (inner.euid, inner.egid, groups)
    } else {
        (inner.uid, inner.gid, groups)
    }
}

pub(crate) fn permission_class_bits(
    meta: &vfs::Metadata,
    uid: u32,
    gid: u32,
    groups: &[u32],
) -> u32 {
    let mode = meta.mode.bits() & 0o777;
    if uid == meta.uid {
        (mode >> 6) & 0o7
    } else if gid == meta.gid || groups.iter().any(|g| *g == meta.gid) {
        (mode >> 3) & 0o7
    } else {
        mode & 0o7
    }
}

pub(crate) fn has_final_access(
    meta: &vfs::Metadata,
    mode: FaccessatMode,
    uid: u32,
    gid: u32,
    groups: &[u32],
) -> bool {
    if mode.bits() == 0 {
        return true;
    }
    if uid == 0 {
        return !mode.contains(FaccessatMode::X_OK) || (meta.mode.bits() & 0o111) != 0;
    }

    let allowed = permission_class_bits(meta, uid, gid, groups);
    if mode.contains(FaccessatMode::R_OK) && (allowed & 0o4) == 0 {
        return false;
    }
    if mode.contains(FaccessatMode::W_OK) && (allowed & 0o2) == 0 {
        return false;
    }
    if mode.contains(FaccessatMode::X_OK) && (allowed & 0o1) == 0 {
        return false;
    }
    true
}

pub(crate) fn has_search_access(meta: &vfs::Metadata, uid: u32, gid: u32, groups: &[u32]) -> bool {
    uid == 0 || (permission_class_bits(meta, uid, gid, groups) & 0o1) != 0
}

static DAC_PARENT_SEARCH_CALLS: AtomicUsize = AtomicUsize::new(0);
static DAC_PARENT_SEARCH_TICKS: AtomicUsize = AtomicUsize::new(0);

pub(crate) fn reset_dac_parent_search_calls() {
    DAC_PARENT_SEARCH_CALLS.store(0, Ordering::Relaxed);
    DAC_PARENT_SEARCH_TICKS.store(0, Ordering::Relaxed);
}

pub(crate) fn dac_parent_search_calls() -> usize {
    DAC_PARENT_SEARCH_CALLS.load(Ordering::Relaxed)
}

pub(crate) fn dac_parent_search_ticks() -> usize {
    DAC_PARENT_SEARCH_TICKS.load(Ordering::Relaxed)
}

#[cfg(feature = "perf_diag")]
struct DacTicksGuard(usize);
#[cfg(feature = "perf_diag")]
impl Drop for DacTicksGuard {
    fn drop(&mut self) {
        DAC_PARENT_SEARCH_TICKS.fetch_add(
            crate::timer::get_time().wrapping_sub(self.0) as usize,
            Ordering::Relaxed,
        );
    }
}

pub(crate) fn check_parent_search_access(
    start: &Arc<dyn vfs::IndexNode>,
    path: &str,
    uid: u32,
    gid: u32,
    groups: &[u32],
) -> isize {
    // perf_diag: count calls and measure ticks
    #[cfg(feature = "perf_diag")]
    {
        DAC_PARENT_SEARCH_CALLS.fetch_add(1, Ordering::Relaxed);
        let _t0 = crate::timer::get_time();
        let _guard = DacTicksGuard(_t0);
    }
    let components = parse_path(path);
    let base = if path.starts_with('/') {
        crate::fs::current_root_inode()
    } else {
        start.clone()
    };

    let check_dir = |inode: &Arc<dyn vfs::IndexNode>| -> isize {
        let meta = match inode.metadata() {
            Ok(meta) => meta,
            Err(e) => return -(e as isize),
        };
        if meta.file_type != FileType::Dir {
            return ENOTDIR;
        }
        if !has_search_access(&meta, uid, gid, groups) {
            return EACCES;
        }
        SUCCESS
    };

    let result = check_dir(&base);
    if result != SUCCESS {
        return result;
    }

    let mut prefix = String::new();
    for (idx, name) in components
        .iter()
        .take(components.len().saturating_sub(1))
        .enumerate()
    {
        if idx > 0 {
            prefix.push('/');
        }
        prefix.push_str(name);
        let inode = match vfs_lookup(&base, &prefix, true) {
            Ok(inode) => inode,
            Err(errno) => return errno,
        };
        let result = check_dir(&inode);
        if result != SUCCESS {
            return result;
        }
    }
    SUCCESS
}

/// Lazy DAC: vfs_lookup first, check parent search permission only on failure.
/// Avoids the double path walk (check_parent_search_access + vfs_lookup) on every call.
/// Semantics preserved: EACCES before ENOENT because if vfs_lookup fails and a parent
/// lacked search permission, we promote the error to EACCES.
pub(crate) fn vfs_lookup_with_dac(
    start: &Arc<dyn vfs::IndexNode>,
    path: &str,
    follow_final: bool,
    uid: u32,
    fsgid: u32,
    groups: &[u32],
) -> Result<Arc<dyn vfs::IndexNode>, isize> {
    match vfs_lookup(start, path, follow_final) {
        Ok(inode) => Ok(inode),
        Err(errno) => {
            let perm = check_parent_search_access(start, path, uid, fsgid, groups);
            if perm != SUCCESS {
                return Err(perm);
            }
            Err(errno)
        }
    }
}

pub(crate) fn check_parent_write_search_access(
    parent: &Arc<dyn vfs::IndexNode>,
    uid: u32,
    gid: u32,
    groups: &[u32],
) -> Result<(), isize> {
    let meta = match parent.metadata() {
        Ok(meta) => meta,
        Err(e) => return Err(-(e as isize)),
    };
    if meta.file_type != FileType::Dir {
        return Err(ENOTDIR);
    }
    if !has_directory_write_search_access(&meta, uid, gid, groups) {
        return Err(EACCES);
    }
    Ok(())
}

bitflags! {
    pub struct MsyncFlags: u32 {
        const MS_ASYNC      =   1;
        const MS_INVALIDATE =   2;
        const MS_SYNC       =   4;
    }
}

// ── xattr (Extended Attributes) ───────────────────────────────────────

pub(crate) const XATTR_USER_PREFIX: &str = "user.";

pub(crate) fn validate_xattr_name(name: &str) -> Result<&str, isize> {
    if !name.starts_with("user.") {
        return Err(ENOTSUP);
    }
    if name.len() <= XATTR_USER_PREFIX.len() {
        return Err(EINVAL);
    }
    if name.len() > 255 {
        return Err(ERANGE);
    }
    Ok(name)
}

pub(crate) fn validate_xattr_flags(flags: u32) -> Result<(), isize> {
    const XATTR_CREATE: u32 = 1;
    const XATTR_REPLACE: u32 = 2;
    match flags {
        0 | XATTR_CREATE | XATTR_REPLACE => Ok(()),
        _ => Err(EINVAL),
    }
}

pub(crate) fn resolve_path_inode(
    path: &str,
    follow_final: bool,
) -> Result<Arc<dyn vfs::IndexNode>, isize> {
    if let Err(errno) = validate_path_len(path) {
        return Err(errno);
    }
    let start = match resolve_start_inode(AT_FDCWD) {
        Ok(inode) => inode,
        Err(errno) => return Err(errno),
    };
    let (uid, fsgid, groups) = caller_ids_and_groups();
    let perm_err = check_parent_search_access(&start, path, uid, fsgid, &groups);
    if perm_err != SUCCESS {
        return Err(perm_err);
    }
    let inode = crate::fs::vfs_lookup(&start, path, follow_final)?;

    // xattrs are only valid on regular files and directories
    if let Ok(md) = inode.metadata() {
        if md.file_type != FileType::File && md.file_type != FileType::Dir {
            return Err(EOPNOTSUPP);
        }
    }

    Ok(inode)
}

pub(crate) fn fd_to_inode(fd: usize) -> Result<Arc<dyn vfs::IndexNode>, isize> {
    let task = current_task().unwrap();
    let files_ref = task.process.files();
    let fd_table = files_ref.lock();
    let file = fd_table.get_file(fd).map_err(|e| -(e as isize))?;

    // O_PATH fd: xattr operations fail with EBADF (check BEFORE xattr capability)
    if is_path_fd(&file) {
        return Err(EBADF);
    }

    let inode = file.inode.clone();
    drop(fd_table);

    // xattrs are only valid on regular files and directories;
    // Linux fgetxattr on pipes/sockets returns EBADF
    if file.file_type() != FileType::File && file.file_type() != FileType::Dir {
        return Err(EBADF);
    }

    Ok(inode)
}
